
;;;; this code was used to build up the html-tags.lisp file,
;;;; it doesn't have much purpose beyond that.

(defun create-html-tags ()
  (with-open-file (str "buildnode/src/html-tags.lisp"  :direction :output :if-exists :supersede )
	 (mapc
	  (lambda (cons)
		 (let ((tag-name (string-downcase (car cons)))
				 (tag-doc (string-trim '(#\Space #\Tab #\Newline)
											  (cadr cons))))
			(let ((tag-name (subseq tag-name 1 (1- (length tag-name)))))
			  (format str "(def-html-tag ~s ~s)~%" tag-name tag-doc))))
	  +shitty-html-def+)
	 ))

(defun create-export-list (&optional (output-str T))
   (mapc
	  (lambda (cons)
		 (let ((tag-name (string-downcase (car cons)))
				 (tag-doc (string-trim '(#\Space #\Tab #\Newline)
											  (cadr cons))))
			(let ((tag-name (subseq tag-name 1 (1- (length tag-name)))))
			  (format output-str "#:~a~%" tag-name tag-doc))))
	  +shitty-html-def+)
  )




(defparameter +shitty-html-def+ 
  '(
(<!--...-->	"Defines a comment")
(<!DOCTYPE> 	"Defines the document type")
(<a>	"Defines an anchor")
(<abbr>	"Defines an abbreviation")
(<acronym>	"Defines an acronym")
(<address>	"Defines an address element")
(<applet>	"Deprecated. Defines an applet")
(<area>	"Defines an area inside an image map")
(<b>	"Defines bold text")
(<base>	"Defines a base URL for all the links in a page")
(<basefont>	"Deprecated. Defines a base font")
(<bdo>	"Defines the direction of text display")
(<big>	"Defines big text")
(<blockquote>	"Defines a long quotation")
(<body>	"Defines the body element")
(<br>	"Inserts a single line break")
(<button>	"Defines a push button")
(<caption>	"Defines a table caption")
(<center>	"Deprecated. Defines centered text")
(<cite>	"Defines a citation")
(<code>	"Defines computer code text")
(<col>	"Defines attributes for table columns ")
(<colgroup>	"Defines groups of table columns")
(<dd>	"Defines a definition description")
(<del>	"Defines deleted text")
(<dir>	"Deprecated. Defines a directory list")
(<div>	"Defines a section in a document")
(<dfn>	"Defines a definition term")
(<dl>	"Defines a definition list")
(<dt>	"Defines a definition term")
(<em>	"Defines emphasized text ")
(<fieldset>	"Defines a fieldset	")
(<font>	"Deprecated. Defines text font, size, and color	")
(<form>	"Defines a form 	")
(<frame>	 "Defines a sub window (a frame)	")
(<frameset>	"Defines a set of frames	")
(<h1> "to <h6>	 Defines header 1 to header 6")
(<head>	"Defines information about the document")
(<hr>	 "Defines a horizontal rule")
(<html>	"Defines an html document")
(<i>	"Defines italic text")
(<iframe>	"Defines an inline sub window (frame)")
(<img>	"Defines an image")
(<input>	"Defines an input field")
(<ins>	"Defines inserted text")
(<isindex>	"Deprecated. Defines a single-line input field")
(<kbd>	"Defines keyboard text")
(<label>	"Defines a label for a form control	<legend>	Defines a title in a fieldset")
(<li>	"Defines a list item	")
(<link>	"Defines a resource reference ")
(<map>	"Defines an image map 	")
(<menu>	"Deprecated. Defines a menu list")
(<meta>	"Defines meta information")
(<noframes>	"Defines a noframe section	")
(<noscript>	"Defines a noscript section	")
(<object>	"Defines an embedded object	")
(<ol>	"Defines an ordered list	")
(<optgroup>	"Defines an option group	")
(<option>	"Defines an option in a drop-down list")
(<p>	"Defines a paragraph	")
(<param>	"Defines a parameter for an object	")
(<pre>	"Defines preformatted text")
(<q>	"Defines a short quotation")
(<s>	"Deprecated. Defines strikethrough text")
(<samp>	"Defines sample computer code	")
(<script>	"Defines a script	")
(<select>	"Defines a selectable list	")
(<small>	"Defines small text	")
(<span>	"Defines a section in a document	")
(<strike>	"Deprecated. Defines strikethrough text	")
(<strong>	"Defines strong text	")
(<style>	"Defines a style definition	")
(<sub>	"Defines subscripted text")
(<sup>	"Defines superscripted text	")
(<table>	"Defines a table	")
(<tbody>	"Defines a table body	")
(<td>	"Defines a table cell	")
(<textarea>	"Defines a text area	")
(<tfoot>	"Defines a table footer	")
(<th>	"Defines a table header	")
(<thead>	"Defines a table header")
(<title>	"Defines the document title")
(<tr>	"Defines a table row")
(<tt>	"Defines teletype text")
(<u>	"Deprecated. Defines underlined text")
(<ul>	"Defines an unordered list")
(<var>	"Defines a variable	")
(<xmp>	"Deprecated. Defines preformatted text")))